config/routes.rb
Aliments::Application.routes.draw do
  root :to => "home#index"

  match 'grupos/listar' => 'grupos#list', :via => [:get, :post]

  
  match 'usuarios/lugares/:id' => 'usuarios#lugares'  
  match 'usuarios/lugares', :via => [:get, :post]
  match 'usuarios/update_lugares/:id' => 'usuarios#update_lugares'
  match 'tipo_medidas/add_tipo/:id' => 'tipo_medidas#add_tipo'
  match 'tipo_medidas/importar/:id' => 'tipo_medidas#importar'
  match 'tipo_medidas/importar'
  match 'tipo_medidas/add_tipo_medida_medidas/:id' => 'tipo_medidas#add_tipo_medida_medidas'

  match 'marcas/marca_alimento/' => 'marcas#marca_alimento', :via => [:get, :post]
  match 'grupos/adicionar_grupo/:id' => 'grupos#adicionar_grupo', :via => [:get, :post]

  match 'alimentos/search'
  match 'alimentos/search_form', :via => [:get, :post]
  match 'alimentos/list', :via => [:get, :post]
  
  match 'alimentos_usda/search'
  match 'alimentos_usda/search_form', :via => [:get, :post]
  match 'alimentos_usda/importar'
  match 'alimentos/importar', :via => [:get, :post]
  match 'alimentos_usda/list', :via => [:get, :post]
  match 'alimentos_usda/importar/:id' => 'alimentos_usda#importar', :via => [:get, :post]
  
  match 'refeicao/listar' => 'refeicaos#list', :via => [:get, :post]
  match 'refeicao/adicionar_alimento/:id'=> 'refeicaos#adicionar_alimento', :via => [:get, :post]
  match 'busca/index' => 'busca#index', :via => [:get, :post]

  
  match 'sessions/fb'=>'sessions#fb'
  match 'sessions/new'=>'sessions#new'
  match 'sessions/create'=>'sessions#create'
  match 'sessions/destroy'=>'sessions#destroy'
  
  resources :alimentos, :alimentos_usda, :usuarios, :tipo_medidas, :medidas, :marcas, :grupos, :lugares, :usuario_lugars, :refeicaos, :componentes
  

end

app/models/componente.rb
class Componente < ActiveRecord::Base
  default_scope :order => 'ordem ASC'
  has_many :componente_alimentos
  has_many :alimentos, :through => :componente_alimentos
end

app/controllers/componentes_controller.rb
class ComponentesController < ApplicationController
  include ApplicationHelper
  include UsuariosHelper
  
  before_filter :authenticate
  before_filter :admin_auth
  
  def index
    @componentes = Componente.order("ordem asc, nome asc")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alimentos }
    end
  end
  
  def create
    @alimento = Alimento.new(params[:alimento])
    
    respond_to do |format|
      if @alimento.save
        format.html { redirect_to(@alimento, :notice => 'Alimento was successfully created.') }
        format.xml  { render :xml => @alimento, :status => :created, :location => @alimento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alimento.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @componente = Componente.find(params[:id])
  end
  
  def new
    @componente = Componente.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @componente }
    end
  end
  
  def update
    @componente = Componente.find(params[:id])
    
    respond_to do |format|
      if @componente.update_attributes(params[:componente])
        format.html { redirect_to(:action=>'index', :notice => 'Nutriente atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @componente.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def create
    @componente = Componente.new(params[:componente])
    @componente.ativo=true
    respond_to do |format|
      if @componente.save
        format.html { redirect_to(:action=>'index', :notice => 'Nutriente criado com sucesso.') }
        format.xml  { render :xml => @componente, :status => :created, :location => @componente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @componente.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @componente = Componente.find(params[:id])
    if(@componente.ativo)
      @componente.ativo=false
    else
      @componente.ativo=true
    end
    
    respond_to do |format|
      if @componente.save
        format.html { redirect_to(:action=>'index', :notice => 'Nutriente criado com sucesso.') }
        format.xml  { render :xml => @componente, :status => :created, :location => @componente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @componente.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/componentes_helper.rb
module ComponentesHelper
end

app/views/componentes/_form.html.erb
<%= form_for(@componente) do |c| %>
	<% if @componente.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@componente.errors.count, "error") %> prohibited this medida from being saved:</h2>
		<ul>
			<% @componente.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="column span-9">
		<fieldset>
			<legend>Nutriente</legend>
			<p class="highlighter">
				<%= c.label :nome, :class=>"title"%>
				<%= c.text_field :nome %>
			</p>
			<p class="highlighter">
				<%= c.label :unidade, :class=>"title"%>
				<%= c.text_field :unidade %>
			</p>
			<p class="highlighter">
				<%= c.label :ordem, :class=>"title"%>
				<%= c.text_field :ordem %>
			</p>
			<p class="highlighter">
				<%= c.label :ativo, :class=>"title"%>
      	<%= c.radio_button :ativo,true %> <%= label_tag(:ativo, "Sim",:class=>"inline") %>
      	<%= c.radio_button :ativo,false %> <%= label_tag(:ativo, "Não",:class=>"inline") %>
			</p>
		</fieldset>
	</div>
	<div class="clear actions">
		<%= c.submit "Salvar", :class => "button"%>
	</div>	
<%end%>

app/views/componentes/edit.html.erb
<h1>Editar Nutriente</h1>
<%=render :partial=> "form"%>

app/views/componentes/index.html.erb
<h1>Lista de Componentes</h1>
<table>
  <thead>
    <tr>
      <td>Nome</td>
      <td>Ativo</td>
      <td>Unidade</td>
      <td>Ordem</td>
      <td></td>
    </tr>
  </thead>
<%@componentes.each do |c|%>
<tr>
  <td><%=c.nome%></td>
  <td><%=c.ativo%></td>
  <td><%=c.unidade%></td>
  <td><%=c.ordem%></td>
  <td><%= link_to 'Editar', edit_componente_path(c) %></td>
  <td><%= link_to 'Excluir', componente_path(c), :confirm => 'Deseja excluir o nutriente?', :method => :delete %></td>
</tr>
<%end%>
</table>
<br />
<%= link_to 'Novo Componente', new_componente_path %>

app/views/componentes/new.html.erb
<h1>Novo Nutriente</h1>
<%=render :partial=> "form"%>