config/routes.rb
Aliments::Application.routes.draw do
  root :to => "home#index"

  match 'grupos/listar' => 'grupos#list', :via => [:get, :post]

  
  match 'usuarios/lugares/:id' => 'usuarios#lugares'  
  match 'usuarios/lugares', :via => [:get, :post]
  match 'usuarios/update_lugares/:id' => 'usuarios#update_lugares'
  match 'tipo_medidas/add_tipo/:id' => 'tipo_medidas#add_tipo'
  match 'tipo_medidas/importar/:id' => 'tipo_medidas#importar'
  match 'tipo_medidas/importar'
  match 'tipo_medidas/add_tipo_medida_medidas/:id' => 'tipo_medidas#add_tipo_medida_medidas'

  match 'marcas/marca_alimento/' => 'marcas#marca_alimento', :via => [:get, :post]
  match 'grupos/adicionar_grupo/:id' => 'grupos#adicionar_grupo', :via => [:get, :post]

  match 'alimentos/search'
  match 'alimentos/search_form', :via => [:get, :post]
  match 'alimentos/list', :via => [:get, :post]
  
  match 'alimentos_usda/search'
  match 'alimentos_usda/search_form', :via => [:get, :post]
  match 'alimentos_usda/importar'
  match 'alimentos/importar', :via => [:get, :post]
  match 'alimentos_usda/list', :via => [:get, :post]
  match 'alimentos_usda/importar/:id' => 'alimentos_usda#importar', :via => [:get, :post]
  
  match 'refeicao/listar' => 'refeicaos#list', :via => [:get, :post]
  match 'refeicao/adicionar_alimento/:id'=> 'refeicaos#adicionar_alimento', :via => [:get, :post]
  match 'busca/index' => 'busca#index', :via => [:get, :post]

  
  match 'sessions/fb'=>'sessions#fb'
  match 'sessions/new'=>'sessions#new'
  match 'sessions/create'=>'sessions#create'
  match 'sessions/destroy'=>'sessions#destroy'
  
  resources :alimentos, :alimentos_usda, :usuarios, :tipo_medidas, :medidas, :marcas, :grupos, :lugares, :usuario_lugars, :refeicaos, :componentes
  

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/alimento.rb
class Alimento < ActiveRecord::Base
  validates_presence_of :nome, :porcao
  has_one :usuario_aprovacao, :class_name => "Usuario", :foreign_key => "usuario_aprovacao_id"
  has_one :usuario_cadastro, :class_name => "Usuario", :foreign_key => "usuario_cadastro_id"

  belongs_to :marca

  has_many :componente_alimentos, :dependent => :destroy
  has_many :componentes, :through => :componente_alimentos, :conditions => ['componentes.ativo = ?',true]

  has_many :grupo_alimentos, :dependent => :destroy
  has_many :grupos, :through => :grupo_alimentos

  has_many :alimento_medidas, :dependent => :destroy
  has_many :medidas, :through => :alimento_medidas
  
  has_many :alimento_tags

  accepts_nested_attributes_for :componente_alimentos,:allow_destroy => true
  accepts_nested_attributes_for :alimento_medidas,:allow_destroy => true
  accepts_nested_attributes_for :grupo_alimentos,:allow_destroy => true
  accepts_nested_attributes_for :marca

  accepts_nested_attributes_for :alimento_tags, :allow_destroy => :true,:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? }}
  
  searchable do
      text :nome, :stored => true
      long :id, :stored => true
      boolean :ativo, :using => :ativo?
      #text :tag_nomes do
      #  alimento_tags.map { |tag| tag.nome}
      #end
  end

end

app/models/alimento_tags.rb
class AlimentoTags < ActiveRecord::Base
  belongs_to :alimento
end

app/models/alimento_usda.rb
class AlimentoUsda < ActiveRecord::Base
    validates_presence_of :nome

    has_many :componente_usda_alimentos, :dependent => :destroy
    has_many :componente_usdas, :through => :componente_usda_alimentos, :conditions => ['componente_usdas.ativo = ?',true]

    searchable do
        text :nome
        boolean :ativo, :using => :ativo?
    end

end

app/models/componente.rb
class Componente < ActiveRecord::Base
  default_scope :order => 'ordem ASC'
  has_many :componente_alimentos
  has_many :alimentos, :through => :componente_alimentos
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
    validates_presence_of :nome
    has_many :grupo_alimentos
    has_many :alimentos, :through => :grupo_alimentos
end

app/models/imagem.rb
class Imagem < ActiveRecord::Base
end

app/models/imagem_tipo.rb
class ImagemTipo < ActiveRecord::Base
end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
  validates_presence_of :nome,:endereco,:numero,:cep,:cidade,:estado
  validates :cep, :presence => true, :length => { :minimum => 8 } unless "#{:cep}".empty?
end

app/models/marca.rb
class Marca < ActiveRecord::Base
  validates_presence_of :nome
  has_many :alimentos
end

app/models/medida.rb
class Medida < ActiveRecord::Base
  validates_presence_of :nome
  has_many :medida_tipo_medidas, :dependent => :destroy
  has_many :tipo_medidas, :through => :medida_tipo_medidas

  has_many :alimento_medidas, :dependent => :destroy
  has_many :alimentos, :through => :alimento_medidas
  
  accepts_nested_attributes_for :medida_tipo_medidas,:allow_destroy => true
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  validates_presence_of :nome
  has_many :usuarios
end

app/models/peso.rb
class Peso < ActiveRecord::Base
  validates_presence_of :peso
  
  belongs_to :usuario
end

app/models/refeicao.rb
class Refeicao < ActiveRecord::Base
  belongs_to :tipo_refeicao
  belongs_to :usuario
  
  has_many :refeicao_alimentos, :dependent => :destroy
  accepts_nested_attributes_for :refeicao_alimentos,:allow_destroy => true
  
  class << self
    def by_usuario_id(id)
      default_select.where("usuario_id=?",id).includes(:usuario,:tipo_refeicao,{:refeicao_alimentos=>{:alimento=>{:componente_alimentos=>:componente}}})
    end
    def by_usuario_date(date,usuario)
      default_select.where("extract(day from data) = ? AND extract(month from data) = ? AND extract(year from data) = ? AND usuario_id=?", date.day, date.month, date.year,usuario.id).includes(:usuario,:tipo_refeicao,{:refeicao_alimentos=>{:alimento=>{:componente_alimentos=>:componente}}},{:refeicao_alimentos=>{:alimento=>{:grupo_alimentos=>:grupo}}}) 
    end
    def default_select
      select("refeicao.id,refeicao.nome")
    end
  end
end

app/models/tag_alimento.rb
class TagAlimento < ActiveRecord::Base
  belongs_to :alimento
end

app/models/tipo_medida.rb
class TipoMedida < ActiveRecord::Base
  has_many :medida_tipo_medidas
  has_many :medidas, :through => :medida_tipo_medidas
end

app/models/tipo_refeicao.rb
class TipoRefeicao < ActiveRecord::Base
   validates_presence_of :nome
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  include UsuariosHelper
  include ApplicationHelper
  include ActiveModel::Validations

  validates_presence_of :login, :if => :login_valido?
  validates_presence_of :email, :nome
  validates_presence_of :senha_segura, :if => :senha_valida?
  validates_presence_of :senha_flag, :if => :senha_valida?
  validates_presence_of :senha_confirmacao, :if => :senha_valida?
  attr_accessor :atualizar_senha, :senha_flag, :senha_confirmacao, :senha_atual
  attr_protected :id
  belongs_to :perfil

  has_many :usuario_lugars, :dependent => :destroy
  has_many :lugars, :through => :usuario_lugars
  accepts_nested_attributes_for :usuario_lugars,:allow_destroy => true

  has_many :pesos, :dependent => :destroy
  belongs_to :peso

  has_many :refeicaos, :dependent => :destroy

  has_many :imagems, :dependent => :destroy
  accepts_nested_attributes_for :imagems,:allow_destroy => true

  has_many :albums, :dependent => :destroy
  accepts_nested_attributes_for :albums,:allow_destroy => true

  has_many :relacionamentos, :dependent => :destroy
  accepts_nested_attributes_for :relacionamentos,:allow_destroy => true

  def login_valido?
    if :login.nil? && :fb_login.nil?
      return true
    end
    return false
  end

  def senha_valida?
    if :fb_login.nil?
      return atualizar_senha || new_record?
    else
      return false
    end
  end

  validates_each :senha_flag do |record, attr, value|
    record.errors.add attr, 'Confirmação de senha inválida' if (value.to_s[0] != :senha_confirmacao) && !:senha_valida?
  end  

  searchable do
    text :nome, :stored => true
    long :id, :stored => true
  end  

  class << self
    def by_login_senha_segura(login,senha_segura)
      default_select.joins(:perfil,:peso).where("usuarios.login=? and usuarios.senha_segura=?",login,senha_segura).first
    end
    def by_id(id)
      default_select.joins(:perfil,:peso).where("usuarios.id=?",id).first
    end
    def default_select
      select("usuarios.id,usuarios.nome,usuarios.login,usuarios.senha_segura,usuarios.altura,usuarios.nascimento,usuarios.atividade_fisica,usuarios.sexo,usuarios.fb_id,perfils.nome perfil_nome,pesos.peso as peso_peso")
    end
  end
  
end

app/helpers/busca_helper.rb
module BuscaHelper
  def relacionamento?(usuario,relacionado)
    usuario.relacionamentos.each do |r|
      if r.relacionado.id == relacionado.id
        return true
      end
    end
    return false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/shared/_header.html.erb
<div class="cinza1">
  <div class="container">
    <div class="span-8">
      <div class="padding-10">
        <%=image_tag("logo_white.png")%>
      </div>
    </div>
    <div class="span-16 last relative">
      <%unless usuario_logged.nil?%>
      <div class="right">
        <%= link_to "/sessions/destroy",:method=>:delete, :class => ("button red small") do%>
        <%= image_tag "icon_lock.png", :class=>""%>Logout
        <%end%>
      </div>
      <div class="right boxHeader zindex1000 padding-10">
        Bem-vindo <br/> <%=usuario_logged.nome%>
      </div>
      <div class="right boxHeader relative">
        <a href="javascript:void(0)" class="headerBoxLink text-center" title="Clique para saber mais sobre as Necessidades diárias de calorias">
          <span class="text-p">Necessidade diária estimada</span><br/>
		<%if calorias(usuario_logged) > 0%>
          <span class="text-g"><%=number_with_precision(calorias(usuario_logged),:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-pp"> kcal</span>
		<%else%>
			Não preenchido
		<%end%>
          <%= image_tag "seta_white_down.gif", :class=>"absolute seta_down"%>
        </a>
        
        <div class="boxHelper absolute hide">          
          <h4>Necessidade Estimada</h4>
        </div>
      </div>
      <div class="right boxHeader relative zindex1000">
        <a href="javascript:void(0)" class="headerBoxLink text-center" title="Clique para saber mais sobre índice de Massa Corporal">          
          <span class="text-p">IMC</span><br/>
		<%if imc(usuario_logged) > 0%>
          <span class="text-g"><%=number_with_precision(imc(usuario_logged),:precision => 2,:strip_insignificant_zeros => true)%> = <%=imc_nome(usuario_logged)%></span>
		<%else%>
			Não preenchido
		<%end%>
         <%= image_tag "seta_white_down.gif", :class=>"absolute seta_down"%>
        </a>
        <div class="boxHelper absolute hide">          
          <h4>IMC ou Índice de Massa Corporal</h4>
          É uma medida internacional usada para classificar o peso ideal. Possui as seguintes classificações: <br/>
          IMC menor 18,9 -> Baixo Peso<br/>
          IMC entre 19 e 24,9 -> Saudável<br/>
          IMC entre 25 e 29,9 -> Sobrepeso<br/>
          IMC entre 30 e 34,9 -> Obesidade Grau 1<br/>
          IMC entre 35 e 39,9 -> Obesidade Grau 2<br/>
          IMC acima de 40 -> Obesidade Grau 3
        </div>
      </div>      
      <%else%>
      <div class="padding-10">
        <div class="right">
          <%= link_to "/sessions/new",:remote=>true, :class => ("button green") do%>
          <%= image_tag "icon_unlock.png", :class=>""%>
          Login
          <%end%>
        </div>
        <div class="relative">
          <div id="loginForm" class="absolute hide"></div>
        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="laranjaGradient">
  <div class="clear container">
    <div id="menu">
      <div class="right">
		<%= form_tag(:controller=>"busca",:action=>"index") do%>
        	<%=search_field_tag("busca_string",@busca)%>
		<%end%>
      </div>
      <ul>
        <li><a href="javascript:void(0)"><%= image_tag "icon_aliments.png"%>A Aliments</a>
          <%= image_tag "seta_white_down.gif", :class=>"seta_down"%>
        </li>
        <li><a href="javascript:void(0)"><%= image_tag "icon_usuario.png"%>Você</a>
          <%= image_tag "seta_white_down.gif", :class=>"seta_down"%>
        </li>
        <%unless usuario_logged.nil?%>
        <li><a href="javascript:void(0)"><%= image_tag "icon_refeicao.png"%>Sua Alimentação</a>
          <%= image_tag "seta_white_down.gif", :class=>"seta_down"%>
        </li>
        <%end%>
        <%if !usuario_logged.nil? && usuario_admin?%>
        <li><a href="javascript:void(0)">Gerenciamento</a>
          <%= image_tag "seta_white_down.gif", :class=>"seta_down"%>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

<div class="cinza0 border-bottom-cinza border-top-black">
  <div class="clear container">
    <div class="relative " id="subMenu">
      <ul class="">
        <li><a href="" >Quem Somos</a></li>
      </ul>
      <%unless usuario_logged.nil?%>
      <ul class="prepend-2">
        <li class="usuarios"><%= link_to 'Cadastre-se', new_usuario_path if usuario_logged.nil?%></li>
        <li class="usuarios"><%= link_to 'Minhas informações', edit_usuario_path(usuario_logged) unless usuario_logged.nil?%></li>
        <li class="usuarios"><%= link_to 'Meus Lugares', :controller=>"usuarios",:action=>"lugares",:id=>usuario_logged unless usuario_logged.nil?%></li>
      </ul>
      <ul class="prepend-4">
        <li class="refeicaos"><%= link_to 'Minhas Refeições', "/refeicao/listar"%></li>
        <li class="refeicaos"><%= link_to 'Nova Refeição', new_refeicao_path%></li>
      </ul>
      <%else%>
      <ul>
        <li class="usuarios"><%= link_to 'Cadastre-se', new_usuario_path%></li>
        <li class="sessions"><%= link_to 'Login','/sessions/new'%></li>
      </ul>
      
      <%end%>
      <%unless usuario_logged.nil? && usuario_admin?%>
      <ul class="prepend-3">
        <li class="alimentos"><%= link_to 'Alimentos',alimentos_path %></li>
        <li class="alimentos_paths"><%= link_to 'Novo Alimento', new_alimento_path%></li>
        <li class="alimentos_usda"><%= link_to 'Alimentos USDA',{ :controller => "alimentos_usda",:action => "index" }  %></li>
        <li class="medidas"><%= link_to 'Medidas',medidas_path %></li>
        <li class="tipo_medidas"><%= link_to 'Tipo Medidas',tipo_medidas_path %></li>
        <li class="componentes"><%= link_to 'Nutrientes',componentes_path %></li>
        <li class="componentes"><%= link_to 'Novo Nutriente',new_componente_path %></li>
        <li class="grupos"><%= link_to 'Grupos',:action=>"list",:controller=>"grupos" %></li>
      </ul>
      <%end%>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var el = $("#menu");
    var p = $("#subMenu li.<%=controller.controller_name %>");
    var ind;
    var li;
    if(!p || p.length <= 0){
      p = el.find("li.<%=controller.controller_name %>");
      li = p;
    }else{
      ind = p.parent().index();
      li = el.find("ul li").get(ind);
    }
    
    if(li){
      setSubMenu(li);
    }
  });
</script>

app/views/shared/_message.html.erb
<%agora=Time.now.to_i %>
<div class="msg <%=classType%>" id="<%=agora%>">
  <div class="right">
    <%=link_to_function (image_tag ("close.png")),"delete_element(this,'##{agora}')"%>
  </div>
  <%=msg%>
  <div class="clear"></div>
</div>

app/views/shared/_validation.js.erb
$("<%=form%>").find(".error").removeClass("error");
  var obj;
  var error;
<%obj.errors.each do |key,er|%>
  obj = $(".<%=key.to_s.gsub('.','')%>","<%=form%>");
  obj.addClass("error");
  error = obj.find("span.errorMsg");
  if(error == null || error.length <= 0){
    error = document.createElement("span");
    $(error).addClass("errorMsg");
    obj.append(error);
  }
  $(error).html("<%=er%>");
<%end%>