config/routes.rb
Aliments::Application.routes.draw do
  root :to => "home#index"

  match 'grupos/listar' => 'grupos#list', :via => [:get, :post]

  
  match 'usuarios/lugares/:id' => 'usuarios#lugares'  
  match 'usuarios/lugares', :via => [:get, :post]
  match 'usuarios/update_lugares/:id' => 'usuarios#update_lugares'
  match 'tipo_medidas/add_tipo/:id' => 'tipo_medidas#add_tipo'
  match 'tipo_medidas/importar/:id' => 'tipo_medidas#importar'
  match 'tipo_medidas/importar'
  match 'tipo_medidas/add_tipo_medida_medidas/:id' => 'tipo_medidas#add_tipo_medida_medidas'

  match 'marcas/marca_alimento/' => 'marcas#marca_alimento', :via => [:get, :post]
  match 'grupos/adicionar_grupo/:id' => 'grupos#adicionar_grupo', :via => [:get, :post]

  match 'alimentos/search'
  match 'alimentos/search_form', :via => [:get, :post]
  match 'alimentos/list', :via => [:get, :post]
  
  match 'alimentos_usda/search'
  match 'alimentos_usda/search_form', :via => [:get, :post]
  match 'alimentos_usda/importar'
  match 'alimentos/importar', :via => [:get, :post]
  match 'alimentos_usda/list', :via => [:get, :post]
  match 'alimentos_usda/importar/:id' => 'alimentos_usda#importar', :via => [:get, :post]
  
  match 'refeicao/listar' => 'refeicaos#list', :via => [:get, :post]
  match 'refeicao/adicionar_alimento/:id'=> 'refeicaos#adicionar_alimento', :via => [:get, :post]
  match 'busca/index' => 'busca#index', :via => [:get, :post]

  
  match 'sessions/fb'=>'sessions#fb'
  match 'sessions/new'=>'sessions#new'
  match 'sessions/create'=>'sessions#create'
  match 'sessions/destroy'=>'sessions#destroy'
  
  resources :alimentos, :alimentos_usda, :usuarios, :tipo_medidas, :medidas, :marcas, :grupos, :lugares, :usuario_lugars, :refeicaos, :componentes
  

end

app/models/refeicao.rb
class Refeicao < ActiveRecord::Base
  belongs_to :tipo_refeicao
  belongs_to :usuario
  
  has_many :refeicao_alimentos, :dependent => :destroy
  accepts_nested_attributes_for :refeicao_alimentos,:allow_destroy => true
  
  class << self
    def by_usuario_id(id)
      default_select.where("usuario_id=?",id).includes(:usuario,:tipo_refeicao,{:refeicao_alimentos=>{:alimento=>{:componente_alimentos=>:componente}}})
    end
    def by_usuario_date(date,usuario)
      default_select.where("extract(day from data) = ? AND extract(month from data) = ? AND extract(year from data) = ? AND usuario_id=?", date.day, date.month, date.year,usuario.id).includes(:usuario,:tipo_refeicao,{:refeicao_alimentos=>{:alimento=>{:componente_alimentos=>:componente}}},{:refeicao_alimentos=>{:alimento=>{:grupo_alimentos=>:grupo}}}) 
    end
    def default_select
      select("refeicao.id,refeicao.nome")
    end
  end
end

app/controllers/refeicaos_controller.rb
class RefeicaosController < ApplicationController
  include ApplicationHelper
  include UsuariosHelper
  
  before_filter :authenticate
  
  def new
    @refeicao = Refeicao.new
  end
  
  def create
    @refeicao = Refeicao.new(params[:refeicao])
    @refeicao.usuario = usuario_logged
    
    if @refeicao.save
      flash[:success] = "Refeição adicionada com sucesso"
      redirect_to :action=> :list, :data=>@refeicao.data.strftime("%d/%m/%y")
    else
      flash[:error] = "Não foi possível salvar a refeição"
      render :action => "new"
    end
  end
  
  def edit
    @refeicao = Refeicao.find(params[:id])
  end
  
  def update
    @refeicao = Refeicao.find(params[:id])
    if @refeicao.update_attributes(params[:refeicao])
      flash[:success] = "Refeição atualizada com sucesso"
      redirect_to :action=> :list, :data=>@refeicao.data.strftime("%d/%m/%y")
    else
      render :action => "edit"
    end
  end
  
  def list
    if params[:date].nil?
      if(session[:data].nil?)
        @data = Date.today
      else
        @data = session[:data]
      end
    else
      print params[:date][:day]
      print params[:date][:month]
      print params[:date][:year]
      #@data = Date.civil(params[:date][:month].to_i,params[:date][:day].to_i,params[:date][:year].to_i)
      #print params[:date]
      #@data = DateTime.strptime("${params[:date][:day]}/${params[:date][:month]}/${params[:date][:year]}","%d/%m/%y").to_time
      @data = Time.mktime(params[:date][:year],params[:date][:month],params[:date][:day]) 
      session[:data] = @data      
    end
    #@refeicoes = Refeicao.by_usuario_id(usuario_logged.id)
    @grupos = Grupo.all.sort{|a,b| a.nome <=> b.nome}
    @refeicoes = Refeicao.by_usuario_date(@data,usuario_logged)
    #@refeicoes = Refeicao.where(:usuario_id=>usuario_logged.id).sort{|a,b| b.data <=> b.data}
  end
  
  def adicionar_alimento
    alimento = Alimento.find(params[:id])
    @refeicao_alimento = RefeicaoAlimento.new(:alimento => alimento)
  end
  
  def destroy
    @refeicao = Refeicao.find(params[:id])
    
    respond_to do |format|
      if @refeicao.destroy
        format.html { redirect_to(:action=>'list', :notice => 'Nutriente criado com sucesso.') }
        format.xml  { render :xml => @componente, :status => :created, :location => @componente }
      else
        format.html { render :action => "list" }
        format.xml  { render :xml => @componente.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/refeicaos_helper.rb
module RefeicaosHelper
  def componentes_refeicoes(rs)
    comps = {}  
    unless rs.nil? || rs.size <= 0
      rs.each do |r|
        cr = componentes_refeicao(r)
        cr.keys.each do |k|
          comps[k] = 0 if comps[k].nil?
          comps[k] = comps[k] + (cr[k])
        end        
    end
    end
    return comps
  end
  
  def componentes_refeicao(r)
    comps = {}
    unless r.nil?
      r.refeicao_alimentos.each do |ra|
        comps_ra = componentes_refeicao_alimento(ra)
        comps_ra.keys.each do |k|
          comps[k] = 0 if comps[k].nil?
          comps[k] = comps[k] + (comps_ra[k])
        end
      end
    end
    return comps
  end
  
  def componentes_refeicao_alimento(ra)
    comps = {}
    ra.alimento.componente_alimentos.each do |ca|
      comps[ca.componente.id] = 0 if comps[ca.componente.id].nil?
      #logger.info(ca.quantidade)
      comps[ca.componente.id] = comps[ca.componente.id] + ((ca.quantidade / ra.alimento.porcao)*ra.quantidade_gramas) unless ca.quantidade.nil?
    end
    return comps
  end
  
  def refeicoes_data(usuario,date)
    refeicoes = Refeicao.find(:all,:conditions => ["extract(day from data) = ? AND extract(month from data) = ? AND extract(year from data) = ? AND usuario_id=?", date.day, date.month, date.year,usuario.id], :include => [:usuario]).sort{|a,b| b.data <=> b.data}
    #refeicoes = Refeicao.by_usuario_id(usuario.id)
    return refeicoes
  end
  
  def refeicoes(usuario)
    #refeicoes = Refeicao.find(:all,:select=>"refeicao.id,refeicao.nome,usuario.id,refeicao_alimentos.id,refeicao_alimentos.alimento.id,refeicao_alimentos.alimento.componentes.id,refeicao_alimentos.alimento.componentes.nome",:conditions => ["usuario_id=?",usuario.id],:include=>[:usuario,{:refeicao_alimentos=>:alimento}]).sort{|a,b| b.data <=> b.data}
    refeicoes = Refeicao.by_usuario_id(usuario.id)
    return refeicoes
  end
  
  def refeicoes_dias(refeicoes)
    datas = {}
    refeicoes.each do |r|
      data_s = r.data.strftime("%d/%m/%y")
      datas[data_s] = [] if datas[data_s].nil?
      datas[data_s] << r
    end
    return datas
  end
  
  def dias_array(dias)
    ds = []
    dias.each do |k|
      ds <<  Date.strptime(k, "%d/%m/%y")
    end
    return ds
  end
  
  def calorias_refeicoes(refeicoes)
    comps = componentes_refeicoes(refeicoes)
    return comps[208] unless comps.nil?
  end
  
  def getDatasRefeicao
    @datas = Refeicao.count( :group => "DATE(data)",
    #:conditions => ["created_at >= ? ", 7.days.ago],
    :order => "DATE(data) ASC"
    )
  end  
end

app/views/refeicaos/_form.html.erb
<%= form_for(@refeicao) do |f| %>
<div class="">
    <div class=" span-4 <%="error" if @refeicao.errors.on(:tipo_refeicao)%>">
      <%=f.label :tipo_refeicao,:class=>"title"%>
      <%= f.select(:tipo_refeicao_id, TipoRefeicao.find(:all).collect {|p| [ p.nome, p.id ] },{ :include_blank => false})%>
      <label>Escolha o tipo de refeição que realizou</label>
      <span class="errorMsg"><%=@refeicao.errors.on(:tipo_refeicao)%></span>
    </div>  
    <div class=" span-8 <%="error" if @refeicao.errors.on(:data)%>">
    	<%= f.label "Data/Hora",:class=>"title" %>
    	<%= f.datetime_select :data,:start_year => 2000,:time_separator => ':', :datetime_separator => ' / ' %>
      <label>Data e hora em que a refeição foi realizada</label>
      <span class="errorMsg"><%=@refeicao.errors.on(:data)%></span>
    </div>
    <div class="span-3 <%="error" if @refeicao.errors.on(:lugar)%>">
      <%=f.label :lugar,:class=>"title"%>
      <%= f.select(:lugar_id, usuario_logged.lugars.collect {|p| [ p.nome, p.id ] },{ :include_blank => false})%>
      <label>Escolha onde realizou a refeição</label>
      <span class="errorMsg"><%=@refeicao.errors.on(:lugar)%></span>
    </div>
    <div class="clear"></div>
</div>
<div class="prepend-top">  
  <fieldset>
    <h2 class="">Alimentos</h2>
    <label>Encontre e adicione alimentos à sua refeição</label>
    <%=render "/alimentos/search_form", :action_form=>"refeicao"%>
    <div id="refeicao_alimentos">
    <%@refeicao.refeicao_alimentos.each do |ra|%>
      <%=render "/refeicaos/refeicao_alimento",:refeicao_alimento=>ra%>
    <%end%>
    </div>
  </fieldset>
</div>
<div class="actions clear">
	<%= f.submit "Salvar", :class => "button green large"%>
</div>
<%end%>

app/views/refeicaos/_refeicao.html.erb
<div class="clear refeicaoList ">
  <h2 class="text-g">    
    <div class="right">
      <%= link_to edit_refeicao_path(refeicao),:class=>"button small" do%>
      	Editar
      <%end%>
      <%= link_to refeicao, :confirm => 'Deseja excluir a refeição?', :method => :delete, :class=>"button small" do%>
        Excluir
      <%end%>
    </div>
    <a href="javascript:void(0)" class="expand toggleEl tooltip" title="Clique para expandir" rel="{parent:'.refeicaoList'}">
      <span class="text-p plus">[+]</span>
    <%comps_r = componentes_refeicao(refeicao) if comps_r.nil?%>
    <%=refeicao.tipo_refeicao.nome unless refeicao.tipo_refeicao.nil?%>
    <span class="text-pp"> | </span>
    <span class="text-m"><%=number_with_precision(comps_r[208],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-m"> kcal</span>
    </a>
    
  </h2>
  <div class="refeicao_details text-p">
    <div class="span-4">Carboidratos: <span class="text-m"><%=number_with_precision(comps_r[205],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> g</span></div>
    <div class="span-4">Proteínas: <span class="text-m"><%=number_with_precision(comps_r[203],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> g</span></div>
    <div class="span-4">Gordura Total: <span class="text-m"><%=number_with_precision(comps_r[204],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> g</span></div>
    <div class="span-4">Gordura Saturada: <span class="text-m"><%=number_with_precision(comps_r[606],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> g</span></div>
    <div class="span-4">Gordura Trans: <span class="text-m"><%=number_with_precision(comps_r[852],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> g</span></div>
    <div class="span-4">Fibra Alimentar: <span class="text-m"><%=number_with_precision(comps_r[291],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> g</span></div>
    <div class="span-4">Sódio: <span class="text-m"><%=number_with_precision(comps_r[307],:precision => 2,:strip_insignificant_zeros => true)%></span><span class="text-p"> mg</span></div>
    <div class="clear"></div>
  </div>
  <div class="alimentos_list">
    <div class="text-pp text-center">Alimentos Ingeridos</div>
    <div>
      <%refeicao.refeicao_alimentos.each do |ra|%>
      <div class="clear">
        <div class="span-6">
          <%=ra.alimento.nome%><br/>
          <%unless ra.medida.nil?%>
          <span class="text-pp"><%=ra.medida_quantidade%> x</span> <span class="text-p"><%=ra.medida.nome%></span>
          <%end%>
        </div>
        <div class="span-3 last text-p">
          <%=number_with_precision(ra.quantidade_gramas,:precision => 2,:strip_insignificant_zeros => true)%> g |
          <%cal=componentes_refeicao_alimento(ra)[208]%>
          <span class="text-g">
            <%=number_with_precision(cal,:precision => 2,:strip_insignificant_zeros => true)%>
          </span> kcal
        </div>
        <hr/>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/refeicaos/_refeicao_alimento.html.erb
<%agora=Time.now.to_f  %>
<div class="clear refeicao_alimento boxItem">
  <%=hidden_field_tag "refeicao[refeicao_alimentos_attributes][#{agora}][_destroy]",0,:class=>"refeicao_alimento_destroy"%>
  <%=hidden_field_tag "refeicao[refeicao_alimentos_attributes][#{agora}][id]", refeicao_alimento.id%>
  <%=hidden_field_tag "refeicao[refeicao_alimentos_attributes][#{agora}][alimento_id]", (refeicao_alimento.alimento.id unless refeicao_alimento.alimento.nil?)%>
  <div class="right"><%=link_to_function (image_tag("delete.png")), "delete_item(this,'div.refeicao_alimento','input.refeicao_alimento_destroy','Deseja excluir o alimento?');", :class => ""%></div>
  <div class="span-3"><h2><%=refeicao_alimento.alimento.nome unless refeicao_alimento.alimento.nil?%></h2></div>
  <%unless refeicao_alimento.alimento.alimento_medidas.nil? || refeicao_alimento.alimento.alimento_medidas.size <= 0%>
  <div class="span-4">
    <label class="title inline">Medida</label>
    <select class="select_medida" name="refeicao[refeicao_alimentos_attributes][<%=agora%>][medida_id]" onChange="calcula_alimento_medida(this)">
      <option></option>
      <%=refeicao_alimento.alimento.alimento_medidas.each do |am|%>
      <%unless am.quantidade.nil?%>
      <option
      <%unless refeicao_alimento.medida.nil?%>
      <%if (am.medida.id == refeicao_alimento.medida.id)%>
      selected="selected"
      <%end%>
      <%end%>
      value="<%=am.medida.id%>" rel="{'qtd':<%=am.quantidade%>}"><%=am.medida.nome%></option>
      <%end%>
      <%end%>
    </select>
  </div>
  <div class="span-5">
    <label class="title inline">Quantidade</label>
    <%=text_field_tag "refeicao[refeicao_alimentos_attributes][#{agora}][medida_quantidade]",refeicao_alimento.medida_quantidade, :class => "medida_quantidade span-1", :onblur => "calcula_alimento_medida(this)" %>
    <label>Quantidade da medida que foi ingerido</label>
  </div>
  <%end%>
  <div class="span-4 <%="error" if refeicao_alimento.errors.on(:quantidade_gramas)%>">
    <label class="title inline">Peso</label>
    <%=text_field_tag "refeicao[refeicao_alimentos_attributes][#{agora}][quantidade_gramas]",refeicao_alimento.quantidade_gramas, :class => "quantidade_gramas span-2", :onblur => "calcula_alimento_medida(this)"  %> g
    <label>Quantidade em gramas ingerida do alimento</label>
    <span class="errorMsg"><%=refeicao_alimento.errors.on(:quantidade_gramas)%></span>
  </div>
  <div class="clear"></div>
</div>

app/views/refeicaos/adicionar_alimento.js.erb
var div = document.createElement("div");
$(div).html("<%= escape_javascript( render(:partial => "/refeicaos/refeicao_alimento", :locals => {:refeicao_alimento => @refeicao_alimento}) ) %>").hide();
$("#searchResults").fadeOut("fast",function(){
  $(this).html("");
  $("#refeicao_alimentos").append(div);
  $(div).fadeIn('fast');
  $(div).find("select").focus();
});

app/views/refeicaos/edit.html.erb
<h1>Editar Refeição</h1>
<h3>Atualize suas refeições</h3>
<%= render 'form' %>

app/views/refeicaos/list.html.erb
<%comps = componentes_refeicoes(@refeicoes)%>
<div class="span-11">
  <h1>Minhas Refeições</h1>
  <h3>Acompanhe aqui as suas refeições realizadas, e saiba como anda a sua alimentação</h3>
</div>
<div class="span-8 last prepend-top ">
  <span class="text-pp">Data selecionada</span><br/><span class="text-gg"><%=@data.strftime("%d/%m/%y")%></span><br/>
  <span class="text-pp">Foram ingeridas</span><br/>
  <%comps[208]=0 if comps[208].nil?%>
  <span class="text-gg"><%=number_with_precision(comps[208],:precision => 2,:strip_insignificant_zeros => true )%></span> kcal
</div>

<div class="column span-12">  
  Refeições realizadas: <hr/>
  <div class="refeicaoListBox clear prepend-1 span-11 last">
    <%@refeicoes.each do |r|%>
      <!--<span class="text-p"><%=r.data.strftime("%Hh%M")%></span> <%=r.tipo_refeicao.nome%>-->
      <%=render :partial=>"refeicao",:locals=>{:refeicao=>r}%>
    <%end%>
  </div>
  <div class="clear"></div>
  <div class="prepend-top">
  Escolha as datas para visualizar as refeições: <hr/>  
    <%=form_tag :action=>"list",:controller=>"refeicaos",:method=>"post" do%>
      <%=select_date(@data)%>
      <%=button_for "Enviar"%>
    <%end%>
  </div>
</div>
<div class="span-7 column last">
  <span class="text-g">Grupos de alimentos ingeridos</span>
        <%grupos = getGruposInfo(@refeicoes,comps)%>
        <table>
          <thead>
            <tr></tr>
          </thead>
          <tbody>
            <%@grupos.each do |g|%>
            <tr>
              <td><%=g.nome%></td>
              <td><%=number_with_precision(grupos[g] || 0,:precision => 2,:strip_insignificant_zeros => true )%></td>
            </tr>
            <%end%>
          </tbody>
        </table>
</div>

app/views/refeicaos/list_old.html.erb
<div class="span-10 column">
  <h1>Minhas Refeições</h1>
  <h3>Acompanhe aqui as suas refeições realizadas, e saiba como anda a sua alimentação</h3>
  <div class="refeicaoListBox">
    <%unless refeicoes.nil? || refeicoes.size <= 0%>
    <%refeicoes_dias = refeicoes_dias(refeicoes)%>
    <%comps_refeicoes = componentes_refeicoes(refeicoes_dias[@data.strftime("%d/%m/%y")])%>
    <%unless refeicoes_dias.nil? || @data.nil? || refeicoes_dias[@data.strftime("%d/%m/%y")].nil?%>
    <%refeicoes_dias[@data.strftime("%d/%m/%y")].each do |rf|%>
      <%=render :partial=>"/refeicaos/refeicao",:locals=>{:refeicao=>rf}%>
    <%end%>
    <%end%>
    <%if refeicoes_dias[@data.strftime("%d/%m/%y")].nil? || refeicoes_dias[@data.strftime("%d/%m/%y")].size <= 0%>
    <div class="error">Nenhuma refeição encontrada.</div>
    <%end%>
    <%end%>
  </div>
</div>
<div class="span-9 column last">
  <div class="">
    <div class="span-5">
      <div class="box text-center">
        <div>
          <span class="text-gg"><%=@data.strftime("%d")%></span>
          <span class="text-g">/<%=@data.strftime("%m")%></span>
          <span class="text-g">/<%=@data.strftime("%y")%></span>
        </div>
        <span class="text-p">Você ingeriou</span><br/>
        <span class="text-gg">
          <%unless (comps_refeicoes.nil? || comps_refeicoes.size <= 0)%>
          <%=number_with_precision(comps_refeicoes[208],:precision => 2,:strip_insignificant_zeros => true )%></span> kcal
          <%else%>
          0</span> kcal
          <%end%>
        </div>
      </div>
      <div class="clear">
        <span class="text-g">Grupos de Alimentos</span><br/><span class="small">Confira as porções ingeridas de cada grupo de alimentos</span>
        <br/><hr/>
        <%unless refeicoes_dias[@data.strftime("%d/%m/%y")].nil? || refeicoes_dias[@data.strftime("%d/%m/%y")].size <= 0%>
        <%grupos = getGruposInfo(refeicoes_dias[@data.strftime("%d/%m/%y")],comps_refeicoes)%>
        <table>
          <thead>
            <tr></tr>
          </thead>
          <tbody>
            <%grupos.keys.each do |g|%>
            <tr>
              <td><%=g.nome%></td>
              <td><%=number_with_precision(grupos[g],:precision => 2,:strip_insignificant_zeros => true )%></td>
            </tr>
            <%end%>
          </tbody>
        </table>
        <%end%>
      </div>
    </div>
    <div class="span-4 last">
    </div>
  </div>
  <div class="clear"></div>
  <div class="prepend-top">
    <%unless refeicoes_dias.nil? || refeicoes_dias.size <= 0%>
    <%keys = dias_array(refeicoes_dias.keys)%>
    <%keys.sort.each do |ks|%>
    <%k=ks.strftime("%d/%m/%y")%>
    <%if @data.strftime("%d/%m/%y") != k%>
    <div class="span-2 text-center boxItem padding-4">
      <%=link_to :action=>"list",:data=>k do%>
      <span class="text-p"><%=k%></span><br/>
      <%=number_with_precision(componentes_refeicoes(refeicoes_dias[k])[208],:precision => 2,:strip_insignificant_zeros => true)%> kcal<br/>
      <span class="text-pp">Refeições: </span><%=refeicoes_dias[k].size%>
      <%end%>
    </div>
    <%end%>
    <%end%>
    <%end%>
  </div>

app/views/refeicaos/new.html.erb
<h1>Nova Refeição</h1>
<h3>Fez uma nova refeição? Cadastre-a agora</h3>
<%= render 'form' %>