config/routes.rb
Aliments::Application.routes.draw do
  root :to => "home#index"

  match 'grupos/listar' => 'grupos#list', :via => [:get, :post]

  
  match 'usuarios/lugares/:id' => 'usuarios#lugares'  
  match 'usuarios/lugares', :via => [:get, :post]
  match 'usuarios/update_lugares/:id' => 'usuarios#update_lugares'
  match 'tipo_medidas/add_tipo/:id' => 'tipo_medidas#add_tipo'
  match 'tipo_medidas/importar/:id' => 'tipo_medidas#importar'
  match 'tipo_medidas/importar'
  match 'tipo_medidas/add_tipo_medida_medidas/:id' => 'tipo_medidas#add_tipo_medida_medidas'

  match 'marcas/marca_alimento/' => 'marcas#marca_alimento', :via => [:get, :post]
  match 'grupos/adicionar_grupo/:id' => 'grupos#adicionar_grupo', :via => [:get, :post]

  match 'alimentos/search'
  match 'alimentos/search_form', :via => [:get, :post]
  match 'alimentos/list', :via => [:get, :post]
  
  match 'alimentos_usda/search'
  match 'alimentos_usda/search_form', :via => [:get, :post]
  match 'alimentos_usda/importar'
  match 'alimentos/importar', :via => [:get, :post]
  match 'alimentos_usda/list', :via => [:get, :post]
  match 'alimentos_usda/importar/:id' => 'alimentos_usda#importar', :via => [:get, :post]
  
  match 'refeicao/listar' => 'refeicaos#list', :via => [:get, :post]
  match 'refeicao/adicionar_alimento/:id'=> 'refeicaos#adicionar_alimento', :via => [:get, :post]
  match 'busca/index' => 'busca#index', :via => [:get, :post]

  
  match 'sessions/fb'=>'sessions#fb'
  match 'sessions/new'=>'sessions#new'
  match 'sessions/create'=>'sessions#create'
  match 'sessions/destroy'=>'sessions#destroy'
  
  resources :alimentos, :alimentos_usda, :usuarios, :tipo_medidas, :medidas, :marcas, :grupos, :lugares, :usuario_lugars, :refeicaos, :componentes
  

end

app/models/alimento.rb
class Alimento < ActiveRecord::Base
  validates_presence_of :nome, :porcao
  has_one :usuario_aprovacao, :class_name => "Usuario", :foreign_key => "usuario_aprovacao_id"
  has_one :usuario_cadastro, :class_name => "Usuario", :foreign_key => "usuario_cadastro_id"

  belongs_to :marca

  has_many :componente_alimentos, :dependent => :destroy
  has_many :componentes, :through => :componente_alimentos, :conditions => ['componentes.ativo = ?',true]

  has_many :grupo_alimentos, :dependent => :destroy
  has_many :grupos, :through => :grupo_alimentos

  has_many :alimento_medidas, :dependent => :destroy
  has_many :medidas, :through => :alimento_medidas
  
  has_many :alimento_tags

  accepts_nested_attributes_for :componente_alimentos,:allow_destroy => true
  accepts_nested_attributes_for :alimento_medidas,:allow_destroy => true
  accepts_nested_attributes_for :grupo_alimentos,:allow_destroy => true
  accepts_nested_attributes_for :marca

  accepts_nested_attributes_for :alimento_tags, :allow_destroy => :true,:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? }}
  
  searchable do
      text :nome, :stored => true
      long :id, :stored => true
      boolean :ativo, :using => :ativo?
      #text :tag_nomes do
      #  alimento_tags.map { |tag| tag.nome}
      #end
  end

end

app/controllers/alimentos_controller.rb
class AlimentosController < ApplicationController
  include ApplicationHelper
  include UsuariosHelper
  
  before_filter :authenticate
  before_filter :admin_auth, :except => [:show,:search,:search_form]

  # GET /alimentos
  # GET /alimentos.xml
  def index
    #@alimentos = Alimento.all.sort{|a,b| a.nome <=> b.nome}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alimentos }
    end
  end

  # GET /alimentos/1
  # GET /alimentos/1.xml
  def show
    @alimento = Alimento.find(params[:id])
    @componente_alimentos = ComponenteAlimento.joins(:alimento,:componente).where("alimentos.id = ? and componentes.ativo=?",@alimento.id,true).order("componentes.ordem")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alimento }
    end
  end

  # GET /alimentos/new
  # GET /alimentos/new.xml
  def new
    @alimento = Alimento.new
    componentes = Componente.where("ativo=?",true).order("ordem ASC")
    componentes.each do |c|
      @alimento.componente_alimentos.build({:componente => c})
      #ca = ComponenteAlimento.new(:componente => c)
      #@alimento.componente_alimentos.push(ca)
    end    

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alimento }
    end
  end

  # GET /alimentos/1/edit
  def edit
    @alimento = Alimento.find(params[:id])
    componentes = Componente.where("ativo=true")
    componentes.each do |c|
      existe = false
      @alimento.componente_alimentos.each do |ca|
        existe = true if ca.componente.id == c.id
      end
      unless existe
        ca_new = ComponenteAlimento.new()
        ca_new.alimento = @alimento
        ca_new.componente = c
        @alimento.componente_alimentos << ca_new
      end
    end    

    @alimento.componente_alimentos = @alimento.componente_alimentos.sort_by{|a| a.id}.reverse
    @alimento.alimento_medidas.sort!{|a,b|
      a.medida.nome <=> b.medida.nome
    }
    
=begin
      @remove = []
      over = []      
      @alimento.componente_alimentos.each do |ca|
        if(over.index(ca.componente.id).nil?)
          over << ca.componente.id
        else
          @remove << ca
        end
      end
=end
  end

  # POST /alimentos
  # POST /alimentos.xml
  def create
    @alimento = Alimento.new(params[:alimento])
    @alimento.ativo=true
    respond_to do |format|
      if @alimento.save
        format.html { redirect_to(:action=>'index', :notice => 'Alimento was successfully created.') }
        format.xml  { render :xml => @alimento, :status => :created, :location => @alimento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alimentos/1
  # PUT /alimentos/1.xml
  def update
    @alimento = Alimento.find(params[:id])
    @alimento.ativo=true

    respond_to do |format|
      if @alimento.update_attributes(params[:alimento])
        format.html { redirect_to(:action=>'index', :notice => 'Alimento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alimentos/1
  # DELETE /alimentos/1.xml
  def destroy
    @alimento = Alimento.find(params[:id])
    @alimento.ativo = false
    @alimento.save
    #@alimento.destroy
    respond_to do |format|
      format.html { redirect_to(alimentos_url) }
      format.xml  { head :ok }
    end
  end

  def search
    #@search = Alimento.search(params[:search])
    #@alimentos = Alimento.find(:all, :conditions => ['nome LIKE ? ', '%'+params[:search]+'%'])
    @alimentos = Sunspot.search(Alimento) do
        keywords params["search"],:fields => [:nome]
        with(:ativo).equal_to true
        adjust_solr_params do |sunspot_params|
            sunspot_params[:rows] = 1000
        end
    end
    @action_form = params[:action_form]
    #@alimentos = search.results
  end

  def search_form
    @action_form = params[:action_form]
    respond_to do |format|
      format.js # this renders your rjs file
    end
  end
  
  def list
    ativo = true
    if(params[:ativo] == "false")
      ativo = false
    end
    @alimentos = Alimento.where(:ativo=>ativo).sort{|a,b| a.nome <=> b.nome}
  end
  
  def importar
    alimento = Alimento.find(params[:id])
    @alimento = alimento.clone
    alimento.componente_alimentos.each do |ca|
      comp_a = ca.clone
      comp_a.alimento = @alimento
      @alimento.componente_alimentos << comp_a
    end
    alimento.alimento_medidas.each do |am|
      alimento_m = am.clone
      alimento_m.alimento = @alimento
      @alimento.alimento_medidas << alimento_m
    end
    alimento.grupo_alimentos.each do |ga|
      grupo_a = ga.clone
      grupo_a.alimento = @alimento
      @alimento.grupo_alimentos << grupo_a
    end
    marca = alimento.marca
    @alimento.marca = marca
    
    render :action => "edit"
  end

end

app/helpers/alimentos_helper.rb
module AlimentosHelper
  def getTipoMedidas
    @tipos = TipoMedida.all
  end

  def getGruposAlimentos
    @gruposAlimentos = Grupo.all
  end
  
end

app/views/alimentos/_componente_alimento_form.html.erb
<%agora=Time.now.to_f  %>
<div class="clear">
	<div class="left span-4"><label class="title"><%=ca.componente.nome%></label></div>
  <%=hidden_field_tag "alimento[componente_alimentos_attributes][#{agora}][id]", ca.id,:class=>"componente_alimento_id"%>  
	<%=hidden_field_tag "alimento[componente_alimentos_attributes][#{agora}][componente_id]", ca.componente.id,:class=>"componente_id"%>
	<div class="left span-3"><%= text_field_tag "alimento[componente_alimentos_attributes][#{agora}][quantidade]",ca.quantidade, :class => "span-2"+(ca.componente.id==268?" kj":"" ), :onblur=>(ca.componente.id==208?"setCal(this)":"")%>&nbsp;<%=ca.componente.unidade%></div>
	<div class="clear"></div>
</div>
<hr/>

app/views/alimentos/_form.html.erb
<%= form_for(@alimento) do |f| %>
<% if @alimento.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@alimento.errors.count, "error") %> prohibited this alimento from being saved:</h2>
  <ul>
    <% @alimento.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="column span-9">
  <fieldset>
    <legend>Alimento</legend>
    <p class="highlighter">
      <%= f.label :nome, :class=>"title"%>
      <%= f.text_field :nome %>
    </p>
    
    <div id="marcaForm">
      <p class="marcaSelected highlighter">
        <%= f.label :marca, :class=>"title"%>
        <%=@alimento.marca.nil? ? "Nenhuma" : @alimento.marca.nome%> |
        <%=link_to "Trocar Marca", "/marcas/marca_alimento",:update=>"marcas",:method=> :post,:remote => true, :class=>"button pp" %>
        <%= f.label "Marca atualmente atribuida ao alimento"%>
      </p>
      <div id="marcas" class="hide">
      </div>
    </div>
  </fieldset>
  <fieldset>
    <legend>Grupos</legend>
    <p class="highlighter">
      Adicionar Grupo: <select name="gruposAlimentos" id="select_grupos_alimentos">
        <option>Escolha</option>
        <%= options_from_collection_for_select(getGruposAlimentos, :id, :nome) %>
      </select>
      <button class="button pp" type="button" onclick="javascript:adicionarGrupo(this)">Adicionar</button>
    </p>
    <hr/>
    <div id="grupos_alimentos">
      <%= render '/grupos/grupos_form' , :alimento => @alimento%>
    </div>
  </fieldset>
  <fieldset>
    <legend>Medidas</legend>
    <p class="highlighter">
      Adicionar Grupo: <select name="tipoMedidas" id="selectTipoMedidas">
        <option>Escolha</option>
        <%= options_from_collection_for_select(getTipoMedidas, :id, :nome) %>
      </select> <button class="button pp" type="button" onclick="javascript:loadTipoMedidas(this)">Adicionar</button>
      <label>Adicione um grupo de medias à esse alimento</label>
    </p>
    <hr/>
    <p>
      <button type="button" class="button pp" onclick="importarMedidas(this)">Importar</button>
      <label>Importe medidas de um outro alimento</label>
      <div id="search_form"></div>
    </p>
    <hr/>
    <div>
      <%=link_to_function ("Limpar valores"), "limparValores(this,'fieldset','input.quantidade');", :class => "button pp vermelho right"%>
      <label>Medidas atualmente cadastradas:</label>
    </div>
    <hr/>
    <div id="alimento_medidas">
      <%= render 'tipo_medidas/tipo_medidas_form' , :alimento => @alimento%>
    </div>
  </fieldset>
</div>
<div class="column span-9 last">
  <fieldset>
    <legend>Nutrientes</legend>
    <p>
      <%= f.label :porcao, :class=>"title"%>
      <%= f.text_field :porcao, :class => "span-2"%> &nbsp; g
    </p>
    <hr/>
    <% @alimento.componente_alimentos.sort_by{|c| "#{c.componente.ordem ? c.componente.ordem : 1100}".to_i } .each do |ca|%>
    <%= render '/alimentos/componente_alimento_form', :ca => ca unless !ca.componente.ativo?%>
    <%end%>
  </fieldset>
</div>
<div class="actions">
  <%= f.submit "Salvar", :class => "button green"%>
</div>
<% end %>

app/views/alimentos/_search_editar.html.erb
<tr class="clear">
  <td class="span-8"><%=alimento.stored(:nome)%></td>
  <td class="span-2"><%= link_to 'Exibir', :controller=>"alimentos", :action=>"show", :id=>alimento.stored(:id) %></td>
  <td class="span-2"><%= link_to 'Editar', edit_alimento_path(alimento.stored(:id)) %></td>
  <td class="span-2"><%= link_to 'Importar', :controller=>"alimentos",:action=>"importar",:id=>alimento.stored(:id) %></td>
  <td class="span-2"><%= link_to 'Apagar',{ :controller=>"alimentos",:action=>"destroy",:id=>alimento.stored(:id)},:method=>:delete,:confirm => 'Are you sure?'%></td>
</tr>

app/views/alimentos/_search_editar_all.html.erb
<tr class="clear">
  <td class="span-8"><%=alimento.nome%></td>
  <td class="span-2"><%= link_to 'Exibir', :controller=>"alimentos", :action=>"show", :id=>alimento.id %></td>
  <td class="span-2"><%= link_to 'Editar', edit_alimento_path(alimento) %></td>
  <td class="span-2"><%= link_to 'Importar', :controller=>"alimentos",:action=>"importar",:id=>alimento.id %></td>
  <td class="span-2"><%= link_to 'Apagar',{ :controller=>"alimentos",:action=>"destroy",:id=>alimento.id},:method=>:delete,:confirm => 'Are you sure?'%></td>
</tr>

app/views/alimentos/_search_form.html.erb
<div class="helperContainer">
    <input type="hidden" name="action_search" value="<%=action_form%>"/>
    Buscar alimentos: <input type="text" name="search" onKeyPress="return enter_action(event,'buscar_alimento',this)" class="enter_disable"/> <button type="button" onclick="buscar_alimento(this)" class="button green"><%= image_tag "lupa.png", :class=>""%> Buscar</button>
	
  <table id="searchResults" class="hide"></table>
</div>

app/views/alimentos/_search_import_form.html.erb
<div class="helperContainer">
    Buscar alimentos: <input type="text" name="search" onKeyPress="enter_action(event,'buscar_alimento',this,'<%=@partial%>')" class="enter_disable"/> <button type="button" onclick="buscar_alimento(this)" class="button pp	">Buscar</button>
  <div id="searchResults" class="helperBox hide"></div>
</div>

app/views/alimentos/_search_importar.erb
<tr class="clear">
  <td class="span-8"><%=alimento.stored(:nome)%></td>
  <td class="span-2"><%= link_to 'Importar',{:controller => "tipo_medidas",:action=>"importar", :id => alimento.stored(:id)}, :method => :post, :remote => true, :class=>"button small green" %></td>
</tr>

app/views/alimentos/_search_refeicao.html.erb
<tr class="clear">
  <td class="span-8"><%=alimento.stored(:nome)%><hr/></td>
  <td class="span-2"><%= link_to 'Adicione à sua refeição',{:controller => "refeicaos",:action=>"adicionar_alimento", :id => alimento.stored(:id)}, :method => :post, :remote => true, :class=>"button green"%></td>
</tr>

app/views/alimentos/alimento_tag_form.html.erb
<%agora=Time.now.to_f  %>
<div>
  <%=hidden_field_tag "alimento[alimnto_tags_attributes][#{agora}][id]", tag.id,:class=>"tag_alimento_id"%>  
	<div class="left span-3"><%= text_field_tag "alimento[alimnto_tags_attributes][#{agora}][nome]",tag.nome, :class => "")%></div>
</div>

app/views/alimentos/edit.html.erb
<h1>Editar Alimento</h1>

<%= render '/alimentos/form' %>

<%= link_to 'Show', @alimento %> |
<%= link_to 'Back', alimentos_path %>

app/views/alimentos/list.html.erb
<h1>Todos Base de dados Aliments</h1>
<div class="helperContainer">
  <table id="searchResults">
    <%@alimentos.each do |a|%>
      <%= render "/alimentos/search_editar_all",:alimento => a%>
    <%end%> 
  </table>
</div>

app/views/alimentos/new.html.erb
<h1>Novo Alimento</h1>

<%= render 'form' %>

<%= link_to 'Back', alimentos_path %>

app/views/alimentos/search.js.erb
var el = $("#searchResults");
el.fadeOut('fast',function(){
	$(el).html("");
<%if @alimentos.total > 0%>

<%@alimentos.each_hit_with_result do |hit,a|%>
  	el.append("<%= escape_javascript( render(:partial => "/alimentos/search_#{@action_form}", :locals => {:alimento => hit}) ) %>");
 <%end%>
    $(el).append("<div class=\"clear\"></div>");
  <%else%>
    $(el).append("<div class=\"clear\">Nenhum alimento encontrado</div>");
  <%end%>
	el.fadeIn('fast');
});

app/views/alimentos/search_form.js.erb
var el = $("#search_form");
el.fadeOut('fast',function(){
  el.html("<%= escape_javascript( render(:partial => "/alimentos/search_form/", :locals=>{:action_form => @action_form}) ) %>");
  el.fadeIn('fast');
});